kwargs_dicts = {
    'widowx_reacher-v1': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 1,
        'reward_type' : 1,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-1, -1, -1, -1, -1, -1],
        'action_max': [1, 1, 1, 1, 1, 1],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v2': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 2,
        'reward_type' : 1,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-1, -1, -1, -1, -1, -1],
        'action_max': [1, 1, 1, 1, 1, 1],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
    },
    'widowx_reacher-v3': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 3,
        'reward_type' : 1,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-1, -1, -1, -1, -1, -1],
        'action_max': [1, 1, 1, 1, 1, 1],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v4': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 4,
        'reward_type' : 1,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-1, -1, -1, -1, -1, -1],
        'action_max': [1, 1, 1, 1, 1, 1],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v5': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 1,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-1, -1, -1, -1, -1, -1],
        'action_max': [1, 1, 1, 1, 1, 1],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v6': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 1,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-0.05, -0.025, -0.025, -0.025, -0.05, -0.0005],
        'action_max': [0.05, 0.025, 0.025, 0.025, 0.05, 0.0005],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v7': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 1,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-2, -2, -2, -2, -2, -2],
        'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v8': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 1,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-10, -10, -10, -10, -10, -10],
        'action_max': [10, 10, 10, 10, 10, 10],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v9': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 1,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-1, -1, -1, -1, -1, -1],
        'action_max': [1, 1, 1, 1, 1, 1],
        'alpha_reward': 0.1,
        'reward_coeff': 1000,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v10': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 1,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-1, -1, -1, -1, -1, -1],
        'action_max': [1, 1, 1, 1, 1, 1],
        'alpha_reward': 0.1,
        'reward_coeff': 0.001,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v11': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 1,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-1.5, -1.5, -1.5, -1.5, -1.5, -1.5],
        'action_max': [1.5, 1.5, 1.5, 1.5, 1.5, 1.5],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v12': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 1,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-3, -3, -3, -3, -3, -3],
        'action_max': [3, 3, 3, 3, 3, 3],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v13': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 2,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-1.5, -1.5, -1.5, -1.5, -1.5, -1.5],
        'action_max': [1.5, 1.5, 1.5, 1.5, 1.5, 1.5],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v14': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 3,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-1.5, -1.5, -1.5, -1.5, -1.5, -1.5],
        'action_max': [1.5, 1.5, 1.5, 1.5, 1.5, 1.5],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v15': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 4,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-1.5, -1.5, -1.5, -1.5, -1.5, -1.5],
        'action_max': [1.5, 1.5, 1.5, 1.5, 1.5, 1.5],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v16': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 5,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-1.5, -1.5, -1.5, -1.5, -1.5, -1.5],
        'action_max': [1.5, 1.5, 1.5, 1.5, 1.5, 1.5],
        'alpha_reward': 0.01,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v17': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 6,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-1.5, -1.5, -1.5, -1.5, -1.5, -1.5],
        'action_max': [1.5, 1.5, 1.5, 1.5, 1.5, 1.5],
        'alpha_reward': 0.01,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v18': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 7,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-2, -2, -2, -2, -2, -2],
        'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v19': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 8,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-1.5, -1.5, -1.5, -1.5, -1.5, -1.5],
        'action_max': [1.5, 1.5, 1.5, 1.5, 1.5, 1.5],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v20': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 9,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-1.5, -1.5, -1.5, -1.5, -1.5, -1.5],
        'action_max': [1.5, 1.5, 1.5, 1.5, 1.5, 1.5],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v21': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 10,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-1.5, -1.5, -1.5, -1.5, -1.5, -1.5],
        'action_max': [1.5, 1.5, 1.5, 1.5, 1.5, 1.5],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v22': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 11,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-1.5, -1.5, -1.5, -1.5, -1.5, -1.5],
        'action_max': [1.5, 1.5, 1.5, 1.5, 1.5, 1.5],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v23': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 12,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-1.5, -1.5, -1.5, -1.5, -1.5, -1.5],
        'action_max': [1.5, 1.5, 1.5, 1.5, 1.5, 1.5],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v24': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 13,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-1.5, -1.5, -1.5, -1.5, -1.5, -1.5],
        'action_max': [1.5, 1.5, 1.5, 1.5, 1.5, 1.5],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v25': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 14,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-1.5, -1.5, -1.5, -1.5, -1.5, -1.5],
        'action_max': [1.5, 1.5, 1.5, 1.5, 1.5, 1.5],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v26': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 15,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-2, -2, -2, -2, -2, -2],
        'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v27': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 16,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-2, -2, -2, -2, -2, -2],
        'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v28': {
        'random_position' : True,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 15,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-2, -2, -2, -2, -2, -2],
        'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v29': {
        'random_position' : True,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 16,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-2, -2, -2, -2, -2, -2],
        'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v30': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "arrow",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 6,
        'reward_type' : 17,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-2, -2, -2, -2, -2, -2],
        'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v31': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "arrow",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 6,
        'reward_type' : 18,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-2.5, -2.5, -2.5, -2.5, -2.5, -2.5],
        'action_max': [2.5, 2.5, 2.5, 2.5, 2.5, 2.5],
        'alpha_reward': 0.01,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v32': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "arrow",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 6,
        'reward_type' : 19,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-2.5, -2.5, -2.5, -2.5, -2.5, -2.5],
        'action_max': [2.5, 2.5, 2.5, 2.5, 2.5, 2.5],
        'alpha_reward': 0.01,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v33': {
        'random_position' : False,
        'random_orientation': True,
        'moving_target': False,
        'target_type': "arrow",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 6,
        'reward_type' : 19,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-4, -4, -4, -4, -4, -4],
        'action_max': [4, 4, 4, 4, 4, 4],
        'alpha_reward': 0.01,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v34': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': True,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 15,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-2, -2, -2, -2, -2, -2],
        'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v35': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': "circular_window",
        'obs_type' : 5,
        'reward_type' : 15,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-2, -2, -2, -2, -2, -2],
        'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v36': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': "circular_window_small",
        'obs_type' : 5,
        'reward_type' : 15,
        'action_type' : 1,
        'joint_limits' : "large",
        'action_min': [-2, -2, -2, -2, -2, -2],
        'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v37': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': "circular_window_small",
        'obs_type' : 7,
        'reward_type' : 20,
        'action_type' : 2,
        'joint_limits' : "large",
        'action_min': [-2, -2, -2, -2, -2, -2],
        'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': True,
        'camera_sensor': True,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v38': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 15,
        'action_type' : 2,
        'joint_limits' : "large",
        'action_min': [-2, -2, -2, -2, -2, -2],
        'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v39': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 1,
        'action_type' : 2,
        'joint_limits' : "large",
        'action_min': [-2, -2, -2, -2, -2, -2],
        'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v40': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 15,
        'action_type' : 2,
        'joint_limits' : "large",
        'action_min': [-0.5, -0.5, -0.5, -0.5, -0.5, -0.5],
        'action_max': [0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v41': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 21,
        'action_type' : 2,
        'joint_limits' : "large",
        'action_min': [-2, -2, -2, -2, -2, -2],
        'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v42': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 7,
        'reward_type' : 1,
        'action_type' : 2,
        'joint_limits' : "large",
        'action_min': [-2, -2, -2, -2, -2, -2],
        'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v43': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 7,
        'reward_type' : 1,
        'action_type' : 2,
        'joint_limits' : "large",
        'action_min': [-2, -2, -2, -2, -2, -2],
        'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v44': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 15,
        'action_type' : 2,
        'joint_limits' : "large",
        'action_min': [-2, -2, -2, -2, -2, -2],
        'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 10,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v45': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 15,
        'action_type' : 2,
        'joint_limits' : "large",
        'action_min': [-2, -2, -2, -2, -2, -2],
        'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 1,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v46': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 15,
        'action_type' : 2,
        'joint_limits' : "small",
        'action_min': [-2, -2, -2, -2, -2, -2],
        'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 20,
        'pybullet_action_coeff': 1,
        'widowx_type': "normal"
        },
    'widowx_reacher-v47': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 15,
        'action_type' : 2,
        'joint_limits' : "large",
        'action_min': [-2, -2, -2, -2, -2, -2],
        'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 5,
        'pybullet_action_coeff': 10,
        'widowx_type': "normal"
        },
    'widowx_reacher-v48': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 15,
        'action_type' : 2,
        'joint_limits' : "large",
        'action_min': [-2, -2, -2, -2, -2, -2],
        'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 10,
        'pybullet_action_coeff': 10,
        'widowx_type': "normal"
        },
    'widowx_reacher-v49': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 15,
        'action_type' : 2,
        'joint_limits' : "large",
        'action_min': [-2, -2, -2, -2, -2, -2],
        'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        'reward_coeff': 1,
        'lidar': False,
        'camera_sensor': False,
        'frame_skip': 20,
        'pybullet_action_coeff': 1,
        'widowx_type': "light"
        },
    'ReachingJaco-v1': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 2,
        'action_type' : 2,
        # 'joint_limits' : "large",
        # 'action_min': [-2, -2, -2, -2, -2, -2],
        # 'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        # 'reward_coeff': 1,
        # 'lidar': False,
        # 'camera_sensor': False,
        # 'frame_skip': 20,
        # 'pybullet_action_coeff': 1,
        # 'widowx_type': "light",
        'robot_gains': 0.05
    },
    'ReachingJaco-v2': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 15,
        'action_type' : 2,
        # 'joint_limits' : "large",
        # 'action_min': [-2, -2, -2, -2, -2, -2],
        # 'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        # 'reward_coeff': 1,
        # 'lidar': False,
        # 'camera_sensor': False,
        # 'frame_skip': 20,
        # 'pybullet_action_coeff': 1,
        # 'widowx_type': "light",
        'robot_gains': 0.05
    },
    'ReachingJaco-v3': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 15,
        'action_type' : 2,
        'action_amplitude': 2,
        'observation_amplitude': 1,
        # 'joint_limits' : "large",
        # 'action_min': [-2, -2, -2, -2, -2, -2],
        # 'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        # 'reward_coeff': 1,
        # 'lidar': False,
        # 'camera_sensor': False,
        # 'frame_skip': 20,
        # 'pybullet_action_coeff': 1,
        # 'widowx_type': "light",
        'robot_gains': 0.05
    },
    'ReachingJaco-v4': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 22,
        'action_type' : 2,
        'action_amplitude': 1,
        'observation_amplitude': 1,
        # 'joint_limits' : "large",
        # 'action_min': [-2, -2, -2, -2, -2, -2],
        # 'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        # 'reward_coeff': 1,
        # 'lidar': False,
        # 'camera_sensor': False,
        # 'frame_skip': 20,
        # 'pybullet_action_coeff': 1,
        # 'widowx_type': "light",
        'robot_gains': 0.05
    },
    'ReachingJaco-v5': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 23,
        'action_type' : 2,
        'action_amplitude': 1,
        'observation_amplitude': 1,
        # 'joint_limits' : "large",
        # 'action_min': [-2, -2, -2, -2, -2, -2],
        # 'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        # 'reward_coeff': 1,
        # 'lidar': False,
        # 'camera_sensor': False,
        # 'frame_skip': 20,
        # 'pybullet_action_coeff': 1,
        # 'widowx_type': "light",
        'robot_gains': 0.05
    },
    'ReachingJaco-v6': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 24,
        'action_type' : 2,
        'action_amplitude': 1,
        'observation_amplitude': 1,
        # 'joint_limits' : "large",
        # 'action_min': [-2, -2, -2, -2, -2, -2],
        # 'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        # 'reward_coeff': 1,
        # 'lidar': False,
        # 'camera_sensor': False,
        # 'frame_skip': 20,
        # 'pybullet_action_coeff': 1,
        # 'widowx_type': "light",
        'robot_gains': 0.05
    },
    'ReachingJaco-v7': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 25,
        'action_type' : 2,
        'action_amplitude': 1,
        'observation_amplitude': 1,
        # 'joint_limits' : "large",
        # 'action_min': [-2, -2, -2, -2, -2, -2],
        # 'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        # 'reward_coeff': 1,
        # 'lidar': False,
        # 'camera_sensor': False,
        # 'frame_skip': 20,
        # 'pybullet_action_coeff': 1,
        # 'widowx_type': "light",
        'robot_gains': 0.05
    },
    'ReachingJaco-v8': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 26,
        'action_type' : 2,
        'action_amplitude': 1,
        'observation_amplitude': 1,
        # 'joint_limits' : "large",
        # 'action_min': [-2, -2, -2, -2, -2, -2],
        # 'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        # 'reward_coeff': 1,
        # 'lidar': False,
        # 'camera_sensor': False,
        # 'frame_skip': 20,
        # 'pybullet_action_coeff': 1,
        # 'widowx_type': "light",
        'robot_gains': 0.05
    },
    'ReachingJaco-v9': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 27,
        'action_type' : 2,
        'action_amplitude': 1,
        'observation_amplitude': 1,
        # 'joint_limits' : "large",
        # 'action_min': [-2, -2, -2, -2, -2, -2],
        # 'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        # 'reward_coeff': 1,
        # 'lidar': False,
        # 'camera_sensor': False,
        # 'frame_skip': 20,
        # 'pybullet_action_coeff': 1,
        # 'widowx_type': "light",
        'robot_gains': 0.05
    },
    'ReachingJaco-v10': {
        'random_position' : False,
        'random_orientation': False,
        'moving_target': False,
        'target_type': "sphere",
        'goal_oriented' : False,
        'obstacle': None,
        'obs_type' : 5,
        'reward_type' : 25,
        'action_type' : 2,
        'action_amplitude': 1,
        'observation_amplitude': 1,
        # 'joint_limits' : "large",
        # 'action_min': [-2, -2, -2, -2, -2, -2],
        # 'action_max': [2, 2, 2, 2, 2, 2],
        'alpha_reward': 0.1,
        # 'reward_coeff': 1,
        # 'lidar': False,
        # 'camera_sensor': False,
        # 'frame_skip': 20,
        # 'pybullet_action_coeff': 1,
        # 'widowx_type': "light",
        'robot_gains': 0.005
    },
}
